### ISSUE TITLE
Hubot on talker responds to its own messages, chaos ensues

### ISSUE THREAD

**Issue by rpavlik** [unixcharles/hubot-talker#3]
See https://github.com/github/hubot-scripts/issues/244

although I'm pretty sure that it's easy to see this with just a default hubot + talker: Hubot help gets goofed up when the "shipit" help is displayed. It just so happens that the problem is aggravated with the disassemble one mentioned in the above bug because the response includes the trigger.

**Comment by rpavlik** [comment]
Oh, the only way to stop the endless disassemble loop is to have someone issue a different hubot command - in my case, it was someone asking "what is the vrbot?" in which case it had a different reply to offer.

**Comment by unixcharles** [comment]
Yes, this was my implementation of the infamous suicide command.  

```
hubot echo hubot die
```

I had this issue too with the latest version of hubot, I had the fix locally but didn't push because I couldn't find the time to test it.

I pushed the fix at [162501fb18b4](https://github.com/unixcharles/hubot-talker/commit/162501fb18b4af4e4ee56cf48bca50d0fa5e693b) and bumped the gem to 1.0.2.

Let me know if it fix it for you

**Comment by rpavlik** [comment]
Thanks for the quick turnaround! I tried updating the package requirement to 1.0.2 and pushing to heroku again, but doing "vrbot help" with disassemble.coffee in the scripts list still goes into a loop that only "vrbot die" stops.

**Comment by unixcharles** [comment]
I don't know if its related but I'm having a lot of issue getting heroku to update npm package.

Can you try to run it locally?

or you could look if heroku has updated the package:

```
heroku run cat node_modules/hubot-talker/package.json | grep version
```

**Comment by rpavlik** [comment]
```
[ rpavlik@articuno hubot (master) ] $ heroku run cat node_modules/hubot-talker/package.json | grep version
  "version":     "1.0.2",
```

What I'm running is at https://github.com/vance-group/vrbot

**Comment by unixcharles** [comment]
Okay, sorry. My commit was missing a few lines. Give it a try with 1.0.3

I tested with our own [bot](https://github.com/teambox/teambot) and it seem to work fine!

For now, the nickname is case sensitive btw, so the nickname provided with the `-n` argument must be the same as the one on talker.

**Comment by rpavlik** [comment]
OK, so that works now! (Help turns into a long, long paste...) Thanks!

I had assumed that name was always case sensitive - is there a more robust way of doing this?  (It looks like the talker API tells you what your own nick is on connect - should that be checked?) Furthermore, there are aliases... Looks like there's a need for factoring out a kind of "is_self" method.

**Comment by unixcharles** [comment]
> OK, so that works now! (Help turns into a long, long paste...) Thanks!

Great

> I had assumed that name was always case sensitive - is there a more robust way of doing this? 

Yes, because nick are unique without case sensibility in talker, we could just ignore the case.

> (It looks like the talker API tells you what your own nick is on connect - should that be checked?)

Its how talker work, when you subscribe to a channel you get all the message from that channel even if they come from you.

There is no certitude that the first join event is coming from you.

> Furthermore, there are aliases... Looks like there's a need for factoring out a kind of "is_self" method.

Yes, I'll do that when I have time.
